version: 2

formats:
  - htmlzip
  - epub

search:
  ranking:
    getting_started/*: 2
    guides/*: 2
    how_to/*: 2
    use_cases/*: 2
    reference/*: 1
    index.rst/*: 2

conda:
  environment: docs/readthedocs-environment.yml
