[GLOBAL]
backend_packages = [
    "pants.backend.python",
    "pants.backend.python.lint.black",
]
pants_version = "2.19.0"
remote_cache_read = true
remote_cache_write = true
remote_instance_name = "main"

[black]
config = "./pyproject.toml"

[python]
interpreter_constraints = ['>=3.8.1']

[python-infer]
ambiguity_resolution = "by_source_root"

[source]
marker_filenames = ["pyproject.toml"]
root_patterns = ["*tests", "/"]
