[GLOBAL]
backend_packages = [
    "pants.backend.python",
    "pants.backend.python.lint.black",
    "pants.backend.python.typecheck.mypy",
]
local_store_directories_max_size_bytes = 8000000000
local_store_files_max_size_bytes = 8000000000
local_store_processes_max_size_bytes = 8000000000
pants_version = "2.19.0"
remote_cache_read = true
remote_cache_write = true
remote_instance_name = "main"
remote_store_address = "grpc://44.204.50.6:9092"

[black]
config = "./pyproject.toml"

[python]
interpreter_constraints = ['>=3.8.1']

[python-infer]
ambiguity_resolution = "by_source_root"

[source]
marker_filenames = ["pyproject.toml"]
root_patterns = ["*tests", "/"]
