name: Unit Testing

on:
  push:
    branches:
      - main
  pull_request:

env:
  POETRY_VERSION: "1.6.1"

jobs:
  test:
    runs-on: ubuntu-latest-unit-tester
    steps:
      - name: clear space
        env:
          CI: true
        shell: bash
        run: rm -rf /opt/hostedtoolcache/*
      - uses: actions/checkout@v3
      - name: Set up python
        uses: actions/setup-python@v4
        with:
          python-version: |
            3.8
            3.9
            3.10
      - name: Install Poetry
        uses: snok/install-poetry@v1
        with:
          version: ${{ env.POETRY_VERSION }}
      - uses: pantsbuild/actions/init-pants@v5-scie-pants
        with:
          # v0 makes it easy to bust the cache if needed
          # just increase the integer to start with a fresh cache
          gha-cache-key: v0-py
          named-caches-hash: ${{ hashFiles('**/pyproject.toml') }}
          pants-ci-config: pants.toml
      - name: Check BUILD files
        run: |
          pants tailor --check :: -docs/::
      - name: Run testing
        env:
          CI: true
        shell: bash
        run: poetry run make -s test
