name: Unit Testing

on:
  push:
    branches:
      - main
  pull_request:


env:
  POETRY_VERSION: "1.6.1"


jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      # You can use PyPy versions in python-version.
      # For example, pypy-2.7 and pypy-3.8
      matrix:
        python-version: ["3.10", "3.9", "3.8"]
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python ${{ matrix.python-version }} + Poetry ${{ env.POETRY_VERSION }}
        uses: "./.github/actions/poetry_setup"
        with:
          python-version: ${{ matrix.python-version }}
          poetry-version: ${{ env.POETRY_VERSION }}
          working-directory: ${{ vars.RUNNER_TEMP }}
          cache-key: dev
      - name: Install deps
        shell: bash
        run: poetry install --with dev
      - name: Run testing
        env:
          CI: true
        shell: bash
        run: poetry run make test
